const data = {
  id: "5419735958797682652",
  form_id: "222908663377466",
  ip: "125.26.169.78",
  created_at: "2022-10-19 03:26:35",
  status: "ACTIVE",
  new: "1",
  flag: "0",
  notes: "",
  updated_at: null,
  answers: {
    1: {
      name: "Dtm",
      order: "1",
      text: "ใบดำเนินการด้าน DTM",
      type: "control_head",
    },
    2: {
      name: "input2",
      order: "18",
      text: "ตกลง",
      type: "control_button",
    },
    3: {
      name: "no",
      order: "2",
      text: "เลขที่ใบดำเนินการด้าน DTM",
      type: "control_textbox",
    },
    4: {
      name: "input4",
      order: "3",
      text: "ส่วนของผู้ขอดำเนินการ",
      type: "control_collapse",
    },
    5: {
      name: "company",
      order: "4",
      text: "สังกัด/หน่วยงาน",
      type: "control_radio",
      answer: "Venine cable",
    },
    6: {
      name: "notification_date",
      order: "5",
      sublabels:
        '{"day":"Day","month":"Month","year":"Year","last":"Last Name","hour":"Hour","minutes":"Minutes","litemode":"Date"}',
      text: "วันที่",
      timeFormat: "AM/PM",
      type: "control_datetime",
      answer: [Object],
      prettyFormat: "19/10/2022",
    },
    7: {
      name: "name",
      order: "6",
      text: "ชื่อผู้แจ้ง",
      type: "control_textbox",
      answer: "อารดา   วันทนาสินธุ์",
    },
    12: {
      name: "instead_name",
      order: "8",
      text: "ผู้ขอดำเนินการ",
      type: "control_textbox",
      answer: "อารดา   วันทนาสินธุ์",
    },
    13: {
      name: "instead_depart",
      order: "11",
      text: "แผนก",
      type: "control_textbox",
      answer: "DTM",
    },
    14: {
      name: "instead_post",
      order: "10",
      text: "ตำแหน่ง",
      type: "control_textbox",
      answer: "DTM",
    },
    15: {
      name: "instead",
      order: "7",
      text: "ดำเนินการให้ผู้อื่น",
      type: "control_radio",
      answer: "ดำเนินการทั่วไป",
    },
    16: {
      name: "user",
      order: "12",
      text: "User ใช้งาน",
      type: "control_checkbox",
    },
    17: {
      name: "chocie",
      order: "14",
      text: "รายการขอดำเนินการ",
      type: "control_checkbox",
      answer: [Array],
      prettyFormat: "ขอเปลี่ยนผู้ครอบครอง",
    },
    18: {
      name: "no_mac",
      order: "15",
      text: "หมายเลขเครื่อง",
      type: "control_textbox",
      answer: "-",
    },
    20: {
      name: "detail",
      order: "16",
      text: "วัตถุประสงค์",
      type: "control_textarea",
      answer: "-*",
    },
    21: { name: "divider", order: "13", type: "control_divider" },
    23: {
      name: "browseFiles",
      order: "17",
      text: "Browse Files",
      type: "control_fileupload",
      answer: [],
    },
    24: {
      name: "input24",
      order: "19",
      text: "ส่วนของผู้จัดการฝ่าย",
      type: "control_collapse",
    },
    25: {
      cfname: "Dynamic Dropdowns",
      name: "manager",
      order: "20",
      selectedField: "53201a2d6866be393e000028",
      static: "No",
      text: "ผู้จัดการฝ่าย",
      type: "control_widget",
    },
    26: {
      name: "s_manager",
      order: "21",
      text: "สถานะผู้จัดการฝ่าย",
      type: "control_radio",
      answer: "รอตรวจสอบ",
    },
    27: {
      cfname: "Smooth Signature",
      name: "sig_manager",
      order: "22",
      selectedField: "529467003477f3512000001f",
      static: "No",
      text: "ผู้จัดการฝ่าย",
      type: "control_widget",
    },
    28: {
      name: "input28",
      order: "23",
      text: "ตกลง",
      type: "control_button",
    },
    29: {
      name: "It29",
      order: "24",
      text: "ส่วนของ DTM",
      type: "control_collapse",
    },
    32: {
      name: "approve_it",
      order: "25",
      text: "ผู้อนุมัติ",
      type: "control_dropdown",
      answer: "คุณอาทิตย์  ภาพันธ์",
    },
    33: {
      name: "s_it",
      order: "26",
      text: "สถานะผู้จัดการ DTM",
      type: "control_radio",
      answer: "รอตรวจสอบ",
    },
    34: {
      cfname: "Smooth Signature",
      name: "sig_it",
      order: "28",
      selectedField: "529467003477f3512000001f",
      static: "No",
      text: "ผู้จัดการ DTM",
      type: "control_widget",
    },
    35: {
      name: "actor_it",
      order: "29",
      text: "ผู้ดำเนินการ",
      type: "control_dropdown",
    },
    37: {
      name: "input37",
      order: "31",
      text: "ตกลง",
      type: "control_button",
    },
    38: {
      name: "input38",
      order: "32",
      text: "ส่วนของผู้ขอดำเนินการ",
      type: "control_collapse",
    },
    39: {
      name: "s_name",
      order: "33",
      text: "สถานะผู้ขอดำเนินการ",
      type: "control_radio",
      answer: "รอดำเนินการ",
    },
    40: {
      name: "name_date",
      order: "35",
      sublabels:
        '{"day":"Day","month":"Month","year":"Year","last":"Last Name","hour":"Hour","minutes":"Minutes","litemode":"Date"}',
      text: "วันที่ตรวจรับงาน",
      timeFormat: "AM/PM",
      type: "control_datetime",
    },
    41: {
      cfname: "Smooth Signature",
      name: "sig_name",
      order: "36",
      selectedField: "529467003477f3512000001f",
      static: "No",
      text: "ผู้ขอดำเนินการ",
      type: "control_widget",
    },
    42: {
      name: "input42",
      order: "37",
      text: "ตกลง",
      type: "control_button",
    },
    43: {
      name: "input46",
      order: "27",
      text: "สาเหตุที่ไม่อนุมัติ",
      type: "control_textbox",
    },
    45: {
      name: "cause_cancel",
      order: "34",
      text: "สาเหตุที่ยกเลิก",
      type: "control_textbox",
    },
    52: {
      name: "input52",
      order: "9",
      text: "ชื่อ-นามสกุลภาษาอังกฤษ",
      type: "control_textbox",
    },
    54: {
      name: "input54",
      order: "30",
      text: "สถานะผู้ดำเนินการ",
      type: "control_radio",
      answer: "รอดำเนินการ",
    },
  },
};
